export class uploadADKWrapper {
    id!: string;
    no!: number;
    ba!: string;
    es1!: string;
    kodeSatker!: string;
    uakpb!: string;
    kodeBarang!: string;
    nup!: number;
    nomor!: string;
    dokumenKoreksi!: string;
    nilaiBrutoSemula!: number;
    nilaiBrutoMenjadi!: number;
    selisihBruto!: number;
    nilaiBukuSemula!: number;
    nilaiBukuMenjadi!: number;
    selisihNilaiBuku!: number;
    statAsetSemula!: string;
    statusAsetMenjadi!: string;
    kuantitasLuasSemula!: number;
    kuantitasLuasMenjadi!: number;
    selisihLuas!: number;
    keterangan!: string;
    flagKoreksi!: number;
    statusValidasi!: string;
    tglP14!: Date;
    tglAkhirP14!: Date;
    tahunAudited!: string;
}
